
language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run build
  - npm install coveralls
  - npm test -- -u --coverage

after_success:
- coveralls < coverage/lcov.info