language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- npm run build
- npm install coveralls
- npm test -- -u

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: sKmd9ZldC4WjuHGzoL8SaZz1hBLpCs9pe0AJvenDL19D+gUDHxVwUlMVy9kGsr53EpworjH5zP49xUV+iJ0aMlRYnfUZgUmszhPDSFKSSeLeIqix9qJfY6xxAopeEiJm/8z71eoaUBLqUyrHTKsJ6u6bnKFAbvglQwlG2/pG1v36V1uQYZgNedn+GkdmtafY3uSIBVTRmMCTnLOSIkwd9naAkYCsHvvwOlfX9itRrLQ0xj72Eu1p97qmMAr4zD79ZxTvrTZcMsIpytB3v8fWmQUE7CNMBPVMTBKq1w+J394Hc5UCz3JL74de+RuBsa8xXDhIYJWpNZJVay0CbijXnmzE2aDgxF1qNjV8IgoCN4gZt1QuSqEKA5U+pDfqzOmzWSAcvVne9vvQ+QDgFlbxpMRO6UdR6Yz3kKofynGojoANP/aUxxVuiCsxcxip4LhaJaN3gz506LXrzmzyjx5FXjC2PNDayKeTmnQcPGFkzpr+DjiZ5Wa0m2NJIB5XfPD0orSXZPt02jVP4F1BJrEy3cB41/VBBhq97qfMPWQsNX9d4bGC99nOed7mD7t3qdH0UaD8VqpolXOeaKIshRd6WvNJgpGdQUvt65o31tC4QqkhHinG7Qz77a9SfPIQZKTksGU/1cPRYqFW9Jdkm1ArFs87C64SZBY/bBJit2cVBls=

