const ACTION_TYPE = {
	REQUEST_LOADING: 'REQUEST_LOADING',
	SOCIAL_LOGIN_SUCCESS: 'ADD_SOCIAL_SUCCESS',
	SOCIAL_LOGIN_REDIRECT: 'ADD_SOCIAL_REDIRECT',
	LOGIN_SUCCESSFUL: 'LOGIN_USER',
	LOGIN_FAILED: 'USER_LOGIN_FAIL',
	SIGNUP_START: 'SIGNUP_START',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAIL: 'SIGNUP_FAIL',
	SIGNUP_STOP: 'SIGNUP_STOP',
	MESSAGE: 'MESSAGE',
	LOGOUT: 'LOGOUT_USER'
};
export default ACTION_TYPE;
